<?php
$quantidadeDias = count($linhasPlanilha);
$totalEntradas = array_sum($totaisEntrada);
$totalSaidas = array_sum($totaisSaida);
?>
<div class="relatorio-header">
    <div class="relatorio-header-left">
        <h1 class="relatorio-titulo"><i class="fas fa-table"></i> Planilha de Movimentos <span class="titulo-badge"><?= htmlspecialchars($nomeMes . ' ' . $ano) ?></span></h1>
        <p class="relatorio-subtitulo"><span class="empresa-tag"><i class="fas fa-store"></i> <?= htmlspecialchars($filialNome ?: 'Selecione uma filial') ?></span> <span><i class="fa-regular fa-calendar"></i> <?= date('d/m/Y', strtotime($periodoInicio)) ?> — <?= date('d/m/Y', strtotime($periodoFim)) ?></span> <span><i class="fa-regular fa-clock"></i> <?= $quantidadeDias ?> dia(s) com movimentos</span></p>
    </div>
    <div class="btn-group">
        <a href="<?= URL_BASE ?>/relatorios/diario-planilha?mes=<?= $mes ?>&ano=<?= $ano ?>&filial_id=<?= $filialId ?>&exportar=excel" class="btn btn-success"><i class="fas fa-file-excel"></i> Excel</a>
        <a href="<?= URL_BASE ?>/relatorios/diario-planilha?mes=<?= $mes ?>&ano=<?= $ano ?>&filial_id=<?= $filialId ?>&exportar=pdf" class="btn btn-danger"><i class="fas fa-file-pdf"></i> PDF</a>
        <a href="<?= URL_BASE ?>/transacoes/fechoDiario?filial_id=<?= $filialId ?>&data=<?= date('Y-m-d') ?>" class="btn btn-primary"><i class="fas fa-edit"></i> Fecho Diário</a>
    </div>
</div>

<div class="relatorio-filtros"><form method="GET" class="planilha-filtros"><label>Mês<select name="mes"><?php foreach ($meses as $i => $nome): ?><option value="<?= $i ?>" <?= $i == $mes ? 'selected' : '' ?>><?= htmlspecialchars($nome) ?></option><?php endforeach; ?></select></label><label>Ano<select name="ano"><?php foreach ($anos as $a): ?><option value="<?= $a ?>" <?= $a == $ano ? 'selected' : '' ?>><?= $a ?></option><?php endforeach; ?></select></label><label>Filial<select name="filial_id" required><option value="">Selecione...</option><?php foreach ($filiais as $f): ?><option value="<?= $f['id'] ?>" <?= $filialId == $f['id'] ? 'selected' : '' ?>><?= htmlspecialchars($f['nome']) ?></option><?php endforeach; ?></select></label><button type="submit" class="btn btn-secondary btn-sm"><i class="fas fa-search"></i> Atualizar</button></form></div>

<div class="resumo-consolidado"><div class="resumo-card"><span>Saldo inicial</span><strong><?= number_format($saldoInicial, 2, ',', '.') ?> Kz</strong></div><div class="resumo-card entrada"><span>Total de entradas</span><strong>+ <?= number_format($totalEntradas, 2, ',', '.') ?> Kz</strong></div><div class="resumo-card saida"><span>Total de saídas</span><strong>− <?= number_format($totalSaidas, 2, ',', '.') ?> Kz</strong></div><div class="resumo-card destaque"><span>Saldo final</span><strong class="<?= $saldoFinal >= 0 ? 'positivo' : 'negativo' ?>"><?= number_format($saldoFinal, 2, ',', '.') ?> Kz</strong></div></div>

<div class="planilha-info"><i class="fas fa-circle-info"></i> As colunas abaixo são criadas a partir das categorias que possuem lançamentos no período selecionado. Categorias de <strong>entrada</strong> aumentam o saldo; categorias de <strong>saída</strong> reduzem-no.</div>
<div class="planilha-tabela"><div class="tabela-scroll"><table class="planilha-table"><thead><tr><th rowspan="2">Dia</th><th colspan="<?= max(1, count($colunasEntrada)) ?>" class="coluna-entrada">Entradas</th><th colspan="<?= max(1, count($colunasSaida)) ?>" class="coluna-saida">Saídas</th><th rowspan="2">Saldo</th></tr><tr><?php if ($colunasEntrada): foreach ($colunasEntrada as $coluna): ?><th><?= htmlspecialchars($coluna['nome']) ?></th><?php endforeach; else: ?><th>Sem entradas</th><?php endif; ?><?php if ($colunasSaida): foreach ($colunasSaida as $coluna): ?><th><?= htmlspecialchars($coluna['nome']) ?></th><?php endforeach; else: ?><th>Sem saídas</th><?php endif; ?></tr></thead><tbody><?php if (!$linhasPlanilha): ?><tr><td colspan="<?= 2 + max(1, count($colunasEntrada)) + max(1, count($colunasSaida)) ?>" class="sem-dados"><i class="fas fa-inbox"></i> Não existem movimentos para este período.</td></tr><?php else: foreach ($linhasPlanilha as $linha): ?><tr><td><strong><?= $linha['dia'] ?></strong></td><?php if ($colunasEntrada): foreach ($colunasEntrada as $coluna): ?><td class="valor entrada"><?= number_format($linha['entradas'][$coluna['id']] ?? 0, 2, ',', '.') ?></td><?php endforeach; else: ?><td>—</td><?php endif; ?><?php if ($colunasSaida): foreach ($colunasSaida as $coluna): ?><td class="valor saida"><?= number_format($linha['saidas'][$coluna['id']] ?? 0, 2, ',', '.') ?></td><?php endforeach; else: ?><td>—</td><?php endif; ?><td class="valor saldo <?= $linha['saldo'] >= 0 ? 'positivo' : 'negativo' ?>"><strong><?= number_format($linha['saldo'], 2, ',', '.') ?></strong></td></tr><?php endforeach; endif; ?></tbody><tfoot><tr><td><strong>TOTAL</strong></td><?php if ($colunasEntrada): foreach ($colunasEntrada as $coluna): ?><td class="valor entrada"><strong><?= number_format($totaisEntrada[$coluna['id']] ?? 0, 2, ',', '.') ?></strong></td><?php endforeach; else: ?><td>—</td><?php endif; ?><?php if ($colunasSaida): foreach ($colunasSaida as $coluna): ?><td class="valor saida"><strong><?= number_format($totaisSaida[$coluna['id']] ?? 0, 2, ',', '.') ?></strong></td><?php endforeach; else: ?><td>—</td><?php endif; ?><td class="valor saldo <?= $saldoFinal >= 0 ? 'positivo' : 'negativo' ?>"><strong><?= number_format($saldoFinal, 2, ',', '.') ?></strong></td></tr></tfoot></table></div></div>
<style>
.planilha-filtros{display:flex;flex-wrap:wrap;gap:12px;align-items:end}.planilha-filtros label{display:grid;gap:5px;font-size:12px;font-weight:700;color:var(--muted)}.planilha-filtros select{min-width:130px;padding:9px;border:1px solid var(--border);border-radius:8px;background:#fff}.relatorio-subtitulo{display:flex;flex-wrap:wrap;gap:12px;color:var(--muted);font-size:13px}.resumo-consolidado{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:20px 0}.resumo-card{display:grid;gap:7px;padding:16px;border:1px solid var(--border);border-radius:12px;background:#fff}.resumo-card span{font-size:12px;color:var(--muted)}.resumo-card strong{font-size:17px;color:var(--ink)}.resumo-card.entrada{border-top:3px solid #16a34a}.resumo-card.saida{border-top:3px solid #dc2626}.resumo-card.destaque{border-top:3px solid var(--navy)}.positivo{color:#15803d!important}.negativo{color:#b91c1c!important}.planilha-info{margin:14px 0;padding:12px 14px;border-radius:9px;background:#eff6ff;color:#1e40af;font-size:13px}.planilha-tabela{background:#fff;border:1px solid var(--border);border-radius:12px;overflow:hidden}.tabela-scroll{overflow:auto}.planilha-table{width:100%;border-collapse:collapse;font-size:13px}.planilha-table th,.planilha-table td{padding:12px 14px;border-bottom:1px solid #e5e7eb;text-align:right;white-space:nowrap}.planilha-table th:first-child,.planilha-table td:first-child{text-align:center}.planilha-table thead th{background:#f8fafc;color:#334155}.planilha-table .coluna-entrada{background:#dcfce7;color:#166534;text-align:center}.planilha-table .coluna-saida{background:#fee2e2;color:#991b1b;text-align:center}.planilha-table .entrada{color:#15803d}.planilha-table .saida{color:#b91c1c}.planilha-table .saldo{background:#f8fafc}.planilha-table tfoot{background:#f8fafc}.sem-dados{text-align:center!important;padding:38px!important;color:var(--muted)}@media(max-width:800px){.resumo-consolidado{grid-template-columns:repeat(2,1fr)}.relatorio-header{display:grid;gap:15px}.btn-group{display:flex;flex-wrap:wrap;gap:8px}}@media print{.relatorio-filtros,.btn-group,.sidebar,.topbar{display:none!important}}
</style>
