<div class="modulo-cabecalho">
    <div><h1><i class="fa-solid fa-file-import"></i> Importar movimentos</h1><p>Envie uma planilha e associe as suas colunas aos campos financeiros.</p></div>
    <a class="btn btn-outline" href="<?php echo URL_BASE; ?>/importacao/historico"><i class="fa-solid fa-clock-rotate-left"></i> Histórico</a>
</div>
<div class="importacao-grid">
 <section class="cartao-importacao"><div class="icone-importacao"><i class="fa-solid fa-cloud-arrow-up"></i></div><h2>Enviar ficheiro</h2><p>Formatos aceites: Excel (.xlsx e .xls) ou CSV. O limite é de 10 MB.</p>
 <form method="post" action="<?php echo URL_BASE; ?>/importacao/upload" enctype="multipart/form-data" class="form-importacao"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf_token); ?>"><label for="ficheiro">Planilha de movimentos</label><input required id="ficheiro" type="file" name="ficheiro" accept=".xlsx,.xls,.csv"><button class="btn btn-primary" type="submit"><i class="fa-solid fa-arrow-up-from-bracket"></i> Enviar e continuar</button></form></section>
 <aside class="cartao-ajuda"><h3><i class="fa-solid fa-circle-info"></i> Antes de importar</h3><ul><li>A primeira linha deve conter os cabeçalhos.</li><li>Mapeie Data, Valor, Tipo, Filial e Categoria.</li><li>Linhas com valores inválidos ou erros como <code>#REF!</code> não são gravadas.</li><li>Confirme a pré-visualização antes de processar.</li></ul></aside>
</div>
<style>
.modulo-cabecalho{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:24px}.modulo-cabecalho h1{margin:0;color:var(--navy-deep);font-size:26px}.modulo-cabecalho h1 i{color:var(--green);margin-right:9px}.modulo-cabecalho p{margin:6px 0 0;color:var(--muted)}.importacao-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:20px}.cartao-importacao,.cartao-ajuda{background:var(--white);border:1px solid var(--border);border-radius:14px;padding:28px;box-shadow:var(--shadow-sm)}.cartao-importacao{text-align:center}.icone-importacao{width:58px;height:58px;display:grid;place-items:center;border-radius:14px;background:rgba(34,197,94,.12);color:var(--green-dark);font-size:25px;margin:0 auto 14px}.cartao-importacao h2{margin:0 0 8px}.cartao-importacao p,.cartao-ajuda li{color:var(--muted);font-size:13px;line-height:1.6}.form-importacao{max-width:520px;margin:22px auto 0;text-align:left;display:grid;gap:10px}.form-importacao label{font-weight:700;font-size:13px}.form-importacao input[type=file]{padding:11px;border:1px dashed var(--border);border-radius:8px;background:var(--bg)}.cartao-ajuda h3{margin-top:0;color:var(--navy-deep)}.cartao-ajuda ul{padding-left:20px;margin-bottom:0}@media(max-width:760px){.importacao-grid{grid-template-columns:1fr}.modulo-cabecalho{flex-direction:column}}
</style>
