<?php
require_once CAMINHO_RAIZ.'/core/Controller.php';require_once CAMINHO_RAIZ.'/middleware/AuthMiddleware.php';require_once CAMINHO_RAIZ.'/helpers/SegurancaHelper.php';require_once CAMINHO_RAIZ.'/helpers/AuditoriaHelper.php';
class ImportacaoController extends Controller {
 public function __construct(){(new AuthMiddleware())->exigirPerfil(['super_admin','admin_empresa']);}
 private function empresa(): int {if(($_SESSION['usuario_perfil']??'')==='super_admin' && !empty($_REQUEST['empresa_id']))return (int)$_REQUEST['empresa_id'];return (int)($_SESSION['empresa_id']??0);}
 private function csrf(): bool{return SegurancaHelper::validarTokenCSRF($_POST['csrf_token']??'');}
 public function index():void{$this->renderizar('importacao/index',['tituloPagina'=>'Importar Excel','paginaAtiva'=>'importacao','csrf_token'=>SegurancaHelper::gerarTokenCSRF()]);}
 public function upload():void {if(!$this->csrf()||empty($_FILES['ficheiro'])){$this->falhar('Pedido de importação inválido.');return;}$f=$_FILES['ficheiro'];$ext=strtolower(pathinfo($f['name'],PATHINFO_EXTENSION));if($f['error']!==UPLOAD_ERR_OK||$f['size']>10*1024*1024||!in_array($ext,['xlsx','xls','csv'],true)){$this->falhar('Seleccione um ficheiro .xlsx, .xls ou .csv com no máximo 10 MB.');return;}if(!class_exists('PhpOffice\\PhpSpreadsheet\\IOFactory')){$this->falhar('PhpSpreadsheet não está instalado. Execute composer install.');return;}$dir=CAMINHO_UPLOADS.'/importacoes';if(!is_dir($dir))mkdir($dir,0750,true);$nome=bin2hex(random_bytes(12)).'.'.$ext;$destino=$dir.'/'.$nome;if(!move_uploaded_file($f['tmp_name'],$destino)){$this->falhar('Não foi possível guardar o ficheiro enviado.');return;}$planilha=\PhpOffice\PhpSpreadsheet\IOFactory::load($destino)->getActiveSheet();$linhas=$planilha->toArray(null,true,true,true);$cabecalhos=array_shift($linhas);$_SESSION['importacao_pendente']=['ficheiro'=>$destino,'nome_original'=>$f['name'],'cabecalhos'=>array_values($cabecalhos),'linhas'=>array_slice(array_values($linhas),0,5000)];$this->renderizar('importacao/mapeamento',['tituloPagina'=>'Mapear colunas','paginaAtiva'=>'importacao','cabecalhos'=>array_values($cabecalhos),'preview'=>array_slice($linhas,0,5),'csrf_token'=>SegurancaHelper::gerarTokenCSRF()]);}
 public function processar():void {if(!$this->csrf()||empty($_SESSION['importacao_pendente'])){$this->falhar('A sessão de importação expirou.');return;}$p=$_SESSION['importacao_pendente'];$mapa=$_POST['mapa']??[];$obrig=['data_transacao','valor','tipo','filial_id','categoria_id'];foreach($obrig as $c)if(!in_array($c,$mapa,true)){$this->falhar('Mapeie o campo obrigatório: '.$c.'.');return;}$ini=microtime(true);$bd=Database::obterLigacao();$empresa=$this->empresa();$token=bin2hex(random_bytes(16));$bd->beginTransaction();try{$s=$bd->prepare('INSERT INTO importacoes (empresa_id,usuario_id,nome_arquivo,total_linhas,status,token_reversao) VALUES (:e,:u,:n,:t,"processando",:token)');$s->execute(['e'=>$empresa,'u'=>(int)$_SESSION['usuario_id'],'n'=>$p['nome_original'],'t'=>count($p['linhas']),'token'=>$token]);$id=(int)$bd->lastInsertId();$ins=$bd->prepare('INSERT INTO transacoes (empresa_id,filial_id,categoria_id,usuario_id,tipo,descricao,valor,metodo_pagamento,data_transacao) VALUES (:empresa,:filial,:categoria,:usuario,:tipo,:descricao,:valor,:metodo,:data)');$ok=0;$falhas=0;foreach($p['linhas'] as $n=>$linha){$d=[];foreach($mapa as $campo=>$indice)$d[$campo]=trim((string)($linha[chr(65+(int)$indice)]??''));if($this->invalida($d,$empresa)){$falhas++;continue;}$ins->execute(['empresa'=>$empresa,'filial'=>(int)$d['filial_id'],'categoria'=>(int)$d['categoria_id'],'usuario'=>(int)$_SESSION['usuario_id'],'tipo'=>$d['tipo'],'descricao'=>$d['descricao']??'Importação Excel','valor'=>(float)str_replace(',','.',$d['valor']),'metodo'=>$d['metodo_pagamento']??'numerario','data'=>$d['data_transacao']]);$ok++;}$bd->prepare('UPDATE importacoes SET linhas_importadas=?,linhas_falhadas=?,status="concluida",tempo_processamento_ms=? WHERE id=?')->execute([$ok,$falhas,(int)((microtime(true)-$ini)*1000),$id]);$bd->commit();AuditoriaHelper::registar('importar','importacoes',$id,null,['linhas_importadas'=>$ok,'linhas_falhadas'=>$falhas]);unset($_SESSION['importacao_pendente']);definirFlash('sucesso',"Importação concluída: $ok linhas importadas e $falhas rejeitadas.");$this->redirecionar('importacao/historico');}catch(Throwable $e){$bd->rollBack();$this->falhar('A importação foi anulada por um erro crítico.');}}
 public function historico():void{$s=Database::obterLigacao()->prepare('SELECT * FROM importacoes WHERE empresa_id=:e ORDER BY criado_em DESC');$s->execute(['e'=>$this->empresa()]);$this->renderizar('importacao/historico',['tituloPagina'=>'Histórico de Importações','paginaAtiva'=>'importacao','importacoes'=>$s->fetchAll(),'csrf_token'=>SegurancaHelper::gerarTokenCSRF()]);}
 public function reverter(string $id):void{if(!$this->csrf()){$this->falhar('Token de segurança inválido.');return;}$bd=Database::obterLigacao();$s=$bd->prepare('SELECT * FROM importacoes WHERE id=:id AND empresa_id=:e');$s->execute(['id'=>(int)$id,'e'=>$this->empresa()]);$i=$s->fetch();if(!$i||$i['status']!=='concluida'){$this->falhar('Importação não disponível para reversão.');return;}$bd->prepare('UPDATE importacoes SET status="revertida" WHERE id=?')->execute([$i['id']]);AuditoriaHelper::registar('reverter_importacao','importacoes',(int)$i['id'],$i,null);definirFlash('sucesso','A importação foi marcada como revertida.');$this->redirecionar('importacao/historico');}
 private function invalida(array $d,int $empresa):bool{return preg_match('/#(REF!|DIV\/0!|VALUE!|N\/A)/i',implode(' ',$d))||!ValidacaoHelper::data($d['data_transacao']??'')||!is_numeric(str_replace(',','.',$d['valor']??''))||(float)str_replace(',','.',$d['valor'])<0||!in_array($d['tipo']??'',['venda','compra','custo','devolucao'],true);}
 private function falhar(string $m):void{definirFlash('erro',$m);$this->redirecionar('importacao/index');}
}
