<?php
require_once CAMINHO_RAIZ.'/core/Controller.php'; require_once CAMINHO_RAIZ.'/models/LogAuditoria.php'; require_once CAMINHO_RAIZ.'/models/Usuario.php'; require_once CAMINHO_RAIZ.'/middleware/AuthMiddleware.php'; require_once CAMINHO_RAIZ.'/helpers/SegurancaHelper.php'; require_once CAMINHO_RAIZ.'/helpers/AuditoriaHelper.php';
class LogsController extends Controller {
 private LogAuditoria $logs; private Usuario $usuarios;
 public function __construct(){(new AuthMiddleware())->exigirPerfil(['super_admin','admin_empresa']);$this->logs=new LogAuditoria();$this->usuarios=new Usuario();}
 private function empresaId(): ?int{return ($_SESSION['usuario_perfil']??'')==='super_admin'?null:(int)$_SESSION['empresa_id'];}
 private function filtrosPedido(): array {return ['usuario_id'=>(int)($_GET['usuario_id']??0),'acao'=>trim($_GET['acao']??''),'tabela_afetada'=>trim($_GET['tabela_afetada']??''),'prioridade'=>trim($_GET['prioridade']??''),'inicio'=>$_GET['inicio']??'','fim'=>$_GET['fim']??''];}
 public function index(): void {$f=$this->filtrosPedido();$dados=$this->logs->paginar($f,$this->empresaId(),max(1,(int)($_GET['pagina']??1))); AuditoriaHelper::registar('logs_visualizados', 'logs_auditoria', null, null, ['filtros'=>$f], 'media');$this->renderizar('logs/index',['tituloPagina'=>'Logs de Auditoria','paginaAtiva'=>'logs','logs'=>$dados['itens'],'paginacao'=>$dados,'filtros'=>$f,'usuarios'=>$this->empresaId()===null?$this->usuarios->todos('nome'):$this->usuarios->porEmpresa($this->empresaId()),'opcoesAcoes'=>AuditoriaHelper::opcoesAcoes(),'opcoesTabelas'=>AuditoriaHelper::opcoesTabelas(),'csrf_token'=>SegurancaHelper::gerarTokenCSRF()]);}
 public function detalhes(string $id): void {$log=$this->logs->encontrarVisivel((int)$id,$this->empresaId());if(!$log){http_response_code(404);echo 'Registo não encontrado.';return;}$this->json(['log'=>$log,'dados_antigos'=>json_decode($log['dados_antigos']??'null',true),'dados_novos'=>json_decode($log['dados_novos']??'null',true)]);}
 public function exportar(): void {$f=$this->filtrosPedido();$itens=$this->logs->paginar($f,$this->empresaId(),1,10000)['itens']; AuditoriaHelper::registar('logs_exportados', 'logs_auditoria', null, null, ['formato'=>($_GET['formato']??'csv'),'filtros'=>$f,'total'=>count($itens)], 'alta');$formato=$_GET['formato']??'csv';if($formato==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="logs-auditoria.csv"');$o=fopen('php://output','w');fputcsv($o,['Data','Utilizador','Ação','Tabela','Registo','Prioridade','IP']);foreach($itens as $l)fputcsv($o,[$l['criado_em'],$l['usuario_nome']??'Sistema',AuditoriaHelper::rotuloAcao($l['acao']),AuditoriaHelper::rotuloTabela($l['tabela_afetada']),$l['registo_id'],$l['prioridade'],$l['ip_origem']]);fclose($o);return;} $this->renderizarSemLayout('logs/index',['logs'=>$itens,'modoImpressao'=>true]);}
}
